In [24]:
import pandas as pd
import numpy as np

from pycaret.regression import setup,compare_models
from lightgbm import LGBMRegressor

In [2]:
train=pd.read_csv("C:\\Users\\admin\\Desktop\\GITHUB Projects\\UD\\Regression with abalone dataset\\train.csv")
test=pd.read_csv("C:\\Users\\admin\\Desktop\\GITHUB Projects\\UD\\Regression with abalone dataset\\test.csv")

In [3]:
train

id Sex  Length  Diameter  Height  Whole weight  Whole weight.1  \
0          0   F   0.550     0.430   0.150        0.7715          0.3285   
1          1   F   0.630     0.490   0.145        1.1300          0.4580   
2          2   I   0.160     0.110   0.025        0.0210          0.0055   
3          3   M   0.595     0.475   0.150        0.9145          0.3755   
4          4   I   0.555     0.425   0.130        0.7820          0.3695   
...      ...  ..     ...       ...     ...           ...             ...   
90610  90610   M   0.335     0.235   0.075        0.1585          0.0685   
90611  90611   M   0.555     0.425   0.150        0.8790          0.3865   
90612  90612   I   0.435     0.330   0.095        0.3215          0.1510   
90613  90613   I   0.345     0.270   0.075        0.2000          0.0980   
90614  90614   I   0.425     0.325   0.100        0.3455          0.1525   

       Whole weight.2  Shell weight  Rings  
0              0.1465        0.2400     11  
1              0.2765        0.3200     11  
2              0.0030        0.0050      6  
3              0.2055        0.2500     10  
4              0.1600        0.1975      9  
...               ...           ...    ...  
90610          0.0370        0.0450      6  
90611          0.1815        0.2400      9  
90612          0.0785        0.0815      6  
90613          0.0490        0.0700      6  
90614          0.0785        0.1050      8  

[90615 rows x 10 columns]

In [4]:
test

id Sex  Length  Diameter  Height  Whole weight  Whole weight.1  \
0       90615   M   0.645     0.475   0.155        1.2380          0.6185   
1       90616   M   0.580     0.460   0.160        0.9830          0.4785   
2       90617   M   0.560     0.420   0.140        0.8395          0.3525   
3       90618   M   0.570     0.490   0.145        0.8740          0.3525   
4       90619   I   0.415     0.325   0.110        0.3580          0.1575   
...       ...  ..     ...       ...     ...           ...             ...   
60406  151021   I   0.345     0.260   0.085        0.1775          0.0735   
60407  151022   F   0.525     0.410   0.145        0.8445          0.3885   
60408  151023   I   0.590     0.440   0.155        1.1220          0.3930   
60409  151024   F   0.660     0.525   0.190        1.4935          0.5885   
60410  151025   F   0.430     0.340   0.120        0.4150          0.1525   

       Whole weight.2  Shell weight  
0              0.3125        0.3005  
1              0.2195        0.2750  
2              0.1845        0.2405  
3              0.1865        0.2350  
4              0.0670        0.1050  
...               ...           ...  
60406          0.0265        0.0500  
60407          0.1670        0.2050  
60408          0.2000        0.2650  
60409          0.3575        0.4350  
60410          0.0910        0.0905  

[60411 rows x 9 columns]

In [5]:
target=train.Rings
test_id=test.id

train_1=train.drop(['id','Rings'],axis=1)
test_1=test.drop('id',axis=1)

data=pd.concat([train_1,test_1],axis=0).reset_index(drop=True)

In [6]:
data

Sex  Length  Diameter  Height  Whole weight  Whole weight.1  \
0        F   0.550     0.430   0.150        0.7715          0.3285   
1        F   0.630     0.490   0.145        1.1300          0.4580   
2        I   0.160     0.110   0.025        0.0210          0.0055   
3        M   0.595     0.475   0.150        0.9145          0.3755   
4        I   0.555     0.425   0.130        0.7820          0.3695   
...     ..     ...       ...     ...           ...             ...   
151021   I   0.345     0.260   0.085        0.1775          0.0735   
151022   F   0.525     0.410   0.145        0.8445          0.3885   
151023   I   0.590     0.440   0.155        1.1220          0.3930   
151024   F   0.660     0.525   0.190        1.4935          0.5885   
151025   F   0.430     0.340   0.120        0.4150          0.1525   

        Whole weight.2  Shell weight  
0               0.1465        0.2400  
1               0.2765        0.3200  
2               0.0030        0.0050  
3               0.2055        0.2500  
4               0.1600        0.1975  
...                ...           ...  
151021          0.0265        0.0500  
151022          0.1670        0.2050  
151023          0.2000        0.2650  
151024          0.3575        0.4350  
151025          0.0910        0.0905  

[151026 rows x 8 columns]

In [7]:
data.isna().sum()

Sex               0
Length            0
Diameter          0
Height            0
Whole weight      0
Whole weight.1    0
Whole weight.2    0
Shell weight      0
dtype: int64

In [8]:
data.dtypes

Sex                object
Length            float64
Diameter          float64
Height            float64
Whole weight      float64
Whole weight.1    float64
Whole weight.2    float64
Shell weight      float64
dtype: object

In [9]:
data=pd.get_dummies(data)

In [10]:
data

Length  Diameter  Height  Whole weight  Whole weight.1  \
0        0.550     0.430   0.150        0.7715          0.3285   
1        0.630     0.490   0.145        1.1300          0.4580   
2        0.160     0.110   0.025        0.0210          0.0055   
3        0.595     0.475   0.150        0.9145          0.3755   
4        0.555     0.425   0.130        0.7820          0.3695   
...        ...       ...     ...           ...             ...   
151021   0.345     0.260   0.085        0.1775          0.0735   
151022   0.525     0.410   0.145        0.8445          0.3885   
151023   0.590     0.440   0.155        1.1220          0.3930   
151024   0.660     0.525   0.190        1.4935          0.5885   
151025   0.430     0.340   0.120        0.4150          0.1525   

        Whole weight.2  Shell weight  Sex_F  Sex_I  Sex_M  
0               0.1465        0.2400      1      0      0  
1               0.2765        0.3200      1      0      0  
2               0.0030        0.0050      0      1      0  
3               0.2055        0.2500      0      0      1  
4               0.1600        0.1975      0      1      0  
...                ...           ...    ...    ...    ...  
151021          0.0265        0.0500      0      1      0  
151022          0.1670        0.2050      1      0      0  
151023          0.2000        0.2650      0      1      0  
151024          0.3575        0.4350      1      0      0  
151025          0.0910        0.0905      1      0      0  

[151026 rows x 10 columns]

In [11]:
data=data.drop('Sex_M',axis=1)

In [12]:
data

Length  Diameter  Height  Whole weight  Whole weight.1  \
0        0.550     0.430   0.150        0.7715          0.3285   
1        0.630     0.490   0.145        1.1300          0.4580   
2        0.160     0.110   0.025        0.0210          0.0055   
3        0.595     0.475   0.150        0.9145          0.3755   
4        0.555     0.425   0.130        0.7820          0.3695   
...        ...       ...     ...           ...             ...   
151021   0.345     0.260   0.085        0.1775          0.0735   
151022   0.525     0.410   0.145        0.8445          0.3885   
151023   0.590     0.440   0.155        1.1220          0.3930   
151024   0.660     0.525   0.190        1.4935          0.5885   
151025   0.430     0.340   0.120        0.4150          0.1525   

        Whole weight.2  Shell weight  Sex_F  Sex_I  
0               0.1465        0.2400      1      0  
1               0.2765        0.3200      1      0  
2               0.0030        0.0050      0      1  
3               0.2055        0.2500      0      0  
4               0.1600        0.1975      0      1  
...                ...           ...    ...    ...  
151021          0.0265        0.0500      0      1  
151022          0.1670        0.2050      1      0  
151023          0.2000        0.2650      0      1  
151024          0.3575        0.4350      1      0  
151025          0.0910        0.0905      1      0  

[151026 rows x 9 columns]

In [16]:
train_final=data.loc[:train.index.max(),:].copy()
test_final=data.loc[train.index.max()+1:,:].reset_index(drop=True).copy()

In [18]:
_=setup(data=pd.concat([train_final,target],axis=1),target='Rings')

In [19]:
compare_models()

Processing:   0%|          | 0/77 [00:00<?, ?it/s]

LGBMRegressor(random_state=2328)

In [21]:
lgbm=LGBMRegressor()

lgbm.fit(train_final,target)

LGBMRegressor()

In [22]:
pred=lgbm.predict(test_final)

In [23]:
pred

array([ 9.73114398,  9.66911329, 10.24789429, ..., 11.88994141,
       13.52541294,  8.77124166])

In [25]:
pred=np.round_(pred)

In [26]:
pred

array([10., 10., 10., ..., 12., 14.,  9.])

In [27]:
pred=pred.astype('int')

In [28]:
pred

array([10, 10, 10, ..., 12, 14,  9])

In [29]:
final_pred=pd.concat([test_id,pd.Series(pred,name='Rings')],axis=1)

In [30]:
final_pred

id  Rings
0       90615     10
1       90616     10
2       90617     10
3       90618     10
4       90619      8
...       ...    ...
60406  151021      6
60407  151022      9
60408  151023     12
60409  151024     14
60410  151025      9

[60411 rows x 2 columns]

In [32]:
final_pred.to_csv("C:\\Users\\admin\\Desktop\\GITHUB Projects\\UD\\Regression with abalone dataset\\final_submission.csv",index=False,header=True)